Merge

diff --git a/bin/cake b/bin/cake
--- a/bin/cake
+++ b/bin/cake
@@ -3,44 +3,73 @@
 #
 # Cake is a shell script for invoking CakePHP shell commands
 #
-# CakePHP(tm) :  Rapid Development Framework (http://cakephp.org)
-# Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
+# CakePHP(tm) :  Rapid Development Framework (https://cakephp.org)
+# Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 #
 # Licensed under The MIT License
 # For full copyright and license information, please see the LICENSE.txt
 # Redistributions of files must retain the above copyright notice.
 #
-# @copyright     Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
-# @link          http://cakephp.org CakePHP(tm) Project
+# @copyright     Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
+# @link          https://cakephp.org CakePHP(tm) Project
 # @since         1.2.0
-# @license       http://www.opensource.org/licenses/mit-license.php MIT License
+# @license       https://opensource.org/licenses/mit-license.php MIT License
 #
 ################################################################################
 
 # Canonicalize by following every symlink of the given name recursively
 canonicalize() {
-	NAME="$1"
-	if [ -f "$NAME" ]
-	then
-		DIR=$(dirname -- "$NAME")
-		NAME=$(cd -P "$DIR" > /dev/null && pwd -P)/$(basename -- "$NAME")
-	fi
-	while [ -h "$NAME" ]; do
-		DIR=$(dirname -- "$NAME")
-		SYM=$(readlink "$NAME")
-		NAME=$(cd "$DIR" > /dev/null && cd $(dirname -- "$SYM") > /dev/null && pwd)/$(basename -- "$SYM")
-	done
-	echo "$NAME"
+    NAME="$1"
+    if [ -f "$NAME" ]
+    then
+        DIR=$(dirname -- "$NAME")
+        NAME=$(cd -P "$DIR" > /dev/null && pwd -P)/$(basename -- "$NAME")
+    fi
+    while [ -h "$NAME" ]; do
+        DIR=$(dirname -- "$NAME")
+        SYM=$(readlink "$NAME")
+        NAME=$(cd "$DIR" > /dev/null && cd $(dirname -- "$SYM") > /dev/null && pwd)/$(basename -- "$SYM")
+    done
+    echo "$NAME"
 }
 
-CONSOLE=$(dirname -- "$(canonicalize "$0")")
+# Find a CLI version of PHP
+findCliPhp() {
+    for TESTEXEC in php php-cli /usr/local/bin/php
+    do
+        SAPI=`echo "<?= PHP_SAPI ?>" | $TESTEXEC 2>/dev/null`
+        if [ "$SAPI" = "cli" ]
+        then
+            echo $TESTEXEC
+            return
+        fi
+    done
+    echo "Failed to find a CLI version of PHP; falling back to system standard php executable" >&2
+    echo "php";
+}
+
+# If current path is a symlink, resolve to real path
+realname="$0"
+if [ -L "$realname" ]
+then
+	realname=$(readlink -f "$0")
+fi
+
+CONSOLE=$(dirname -- "$(canonicalize "$realname")")
 APP=$(dirname "$CONSOLE")
 
-if [ $(basename $0) != 'cake' ]
+# If your CLI PHP is somewhere that this doesn't find, you can define a PHP environment
+# variable with the correct path in it.
+if [ -z "$PHP" ]
 then
-    exec php "$CONSOLE"/cake.php $(basename $0) "$@"
+    PHP=$(findCliPhp)
+fi
+
+if [ $(basename $realname) != 'cake' ]
+then
+    exec $PHP "$CONSOLE"/cake.php $(basename $realname) "$@"
 else
-    exec php "$CONSOLE"/cake.php "$@"
+    exec $PHP "$CONSOLE"/cake.php "$@"
 fi
 
 exit
