PB-19212: paratest now with usage examples and parameters

diff --git a/bin/paratest b/bin/paratest
--- a/bin/paratest
+++ b/bin/paratest
@@ -20,14 +20,69 @@ set -euo pipefail
 #  docker ps -a | grep phpunitLAB | awk '{print $1}' | xargs docker rm
 
 TEST_GROUP_SIZE=200
-MYSQL_VERSION=5.7
-# FOR M1 users, use:
-# MYSQL_DOCKER_IMAGE="biarms/mysql"
-# PHP_UNIT_DOCKER_IMAGE="registry.gitlab.com/passbolt/php-test-base-images/8.1-arm64:8.1"
-#
-MYSQL_DOCKER_IMAGE="mysql"
+DATABASE_DOCKER_IMAGE="mysql:5.7"
 PHP_UNIT_DOCKER_IMAGE="registry.gitlab.com/passbolt/php-test-base-images:8.1"
 PIDS=()
+LOG_PATH="tmp/paratest"
+PROGNAME="$0"
+
+usage() {
+
+  cat <<-EOF
+  usage: $PROGNAME [OPTION] [ARGUMENTS]
+
+  Always use this script from the root of the passbolt directory
+
+  OPTIONS:
+
+   -h this help message
+   -d Relational database docker image (default mysql:5.7, intel)
+   -p PHP base docker image (default php 8.1 image)
+   -t test group size (# of tests per group, default 200)
+
+  EXAMPLES:
+
+   Default (only intel):
+   -------------------------------------------
+   bin/paratest
+
+   Intel:
+   -------------------------------------------
+   bin/paratest -d "mysql:5.7" -p "registry.gitlab.com/passbolt/php-test-base-images:8.1"
+
+   M1:
+   -------------------------------------------
+   bin/paratest -d "biarms/mysql" -p "registry.gitlab.com/passbolt/php-test-base-images/8.1-arm64:8.1"
+
+EOF
+}
+
+get_options() {
+
+  local OPTIND=$OPTIND
+
+  while getopts "hd:p:t:" opt; do
+    case $opt in
+      d)
+        DATABASE_DOCKER_IMAGE="$OPTARG"
+        ;;
+      p)
+        PHP_UNIT_DOCKER_IMAGE="$OPTARG"
+        ;;
+      t)
+        TEST_GROUP_SIZE="$OPTARG"
+        ;;
+      h)
+        usage
+        exit 0
+        ;;
+      *)
+        echo "Invalid option"
+        exit 1
+        ;;
+    esac
+  done
+}
 
 cleanup_docker() {
 
@@ -49,7 +104,7 @@ cleanup_docker() {
 calculate_test_groups() {
 
   # Run a mysql container required to run phpunit. Even for running --list-tests??
-  docker run -d --name mysqltestcounter --tmpfs /var/lib/mysql:rw -e MYSQL_USER=test -e MYSQL_PASSWORD=test -e MYSQL_DATABASE=test -e MYSQL_ROOT_PASSWORD=test $MYSQL_DOCKER_IMAGE:$MYSQL_VERSION
+  docker run -d --name mysqltestcounter --tmpfs /var/lib/mysql:rw -e MYSQL_USER=test -e MYSQL_PASSWORD=test -e MYSQL_DATABASE=test -e MYSQL_ROOT_PASSWORD=test $DATABASE_DOCKER_IMAGE
   local DB_HOST=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' mysqltestcounter)
 
   # Get all tests and split them in regex groups
@@ -87,7 +142,7 @@ start_test() {
   local SERVER=$1
   local TEST_GROUP=$2
   local MYSQL_IP=1.1.1.1
-  docker run -d --name mysqltestLAB$SERVER --tmpfs /var/lib/mysql:rw -e MYSQL_USER=test -e MYSQL_PASSWORD=test -e MYSQL_DATABASE=test -e MYSQL_ROOT_PASSWORD=test $MYSQL_DOCKER_IMAGE:$MYSQL_VERSION
+  docker run -d --name mysqltestLAB$SERVER --tmpfs /var/lib/mysql:rw -e MYSQL_USER=test -e MYSQL_PASSWORD=test -e MYSQL_DATABASE=test -e MYSQL_ROOT_PASSWORD=test $DATABASE_DOCKER_IMAGE
   MYSQL_IP=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' mysqltestLAB$SERVER)
 
 	RANDOM_DB_NAME=$(echo $RANDOM)
@@ -98,7 +153,6 @@ start_test() {
       mysqladmin -u root -h ${MYSQL_IP} create test$RANDOM_DB_NAME -ptest
       gpg --import config/gpg/unsecure_private.key > /dev/null 2>&1 && \
       gpg --import config/gpg/unsecure.key > /dev/null 2>&1 && \
-      mkdir -p tmp/paratest && \
       DEBUG=1 \
       PASSBOLT_REGISTRATION_PUBLIC=1 \
       PASSBOLT_SELENIUM_ACTIVE=1 \
@@ -119,6 +173,10 @@ start_test() {
   PIDS+=$(docker inspect -f '{{.State.Pid}}' phpunitLAB$SERVER)
 }
 
+get_options "$@"
+
+mkdir -p $LOG_PATH
+
 # Start the tests in background
 COUNT=0
 for group in $(calculate_test_groups); do
@@ -131,4 +189,4 @@ wait
 cleanup_docker
 
 # Show test results in console
-cat phpunit_test_log*.txt
+cat $LOG_PATH/phpunit_test_log*.txt
